version: '3'
services: 
  gitbucket:
    image: gitbucket/gitbucket:4.37.2
    ports:
      - 8080:8080
      - 29418:29418
    tty: true
    volumes:
      - ./gitbucket-data:/gitbucket
    restart: always